FROM 8.12.0-jessie

# Install npm
RUN apt-get install npm

# Install npm dependencies
RUN	npm install -g npm \
	npm install --save @angular/material @angular/cdk @angular/animations \
	npm install -g @angular/cli \

